### ISSUE TITLE
Não consigo fazer funcionar no Manjaro

### ISSUE THREAD

**Issue by rmonicovia** [andreztz/notify-send#18]
Instalei o gobject-introspection, estou rodando o exemplo do readme:

```python
    from notify import notification
    notification('summary text', message='message body', app_name='myapp')
```

Só retorna `True` mas não mostra nada na tela.

Estou com o dunst rodando.

Como posso fazer para encontrar mais informação?

Obrigado!

**Comment by andreztz** [comment]
@rmonicovia Testei o `dunst` e o problema acontece aqui também. Quando o método `n.close()` é executado, ele diz para o servidor ocultar a notificação da tela imediatamente.   https://github.com/andreztz/notify-send/blob/6a3af3ac11ebe7f1e2c09ef147d3b05ae39ddf81/notify/linux/notify.py#L33

Por hora a solução é remover `n.close()` e retornar `n.show()`. Muito obrigado por reportar o problema.

**Comment by andreztz** [comment]
@rmonicovia problema corrigido na versão [v0.0.20](https://github.com/andreztz/notify-send/releases/tag/v0.0.20)
