### ISSUE TITLE
Unit tests are installed together with the package

### ISSUE THREAD

**Issue by mbdevpl** [andreztz/notify-send#23]
Hello! Thanks for the nice package, I've been using it for quite a while. However, I noticed recently that the package pollutes the Python installation a tiny bit by installing its unit tests together with the actual package. I don't think it's intended, and I don't think it's desirable. Other packages don't really do this, unless their packaging/build is a bit misconfigured, like I think it's the case here. Fortunately this has a simple fix, for which I'll open a PR shortly.

It's visible after installing latest version of the package:

```bash
$ pip install notify-send
...
Successfully installed notify-send-1.1.0
```

And then attempting to uninstall it:

```bash
$ pip uninstall notify-send
Found existing installation: notify-send 1.1.0
Uninstalling notify-send-1.1.0:
  Would remove:
    /home/mateusz/Software/Spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/python-3.11.0-tabbwylcmzsapq3wvci3xdh7ztalg5vm/lib/python3.11/site-packages/notify/*
    /home/mateusz/Software/Spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/python-3.11.0-tabbwylcmzsapq3wvci3xdh7ztalg5vm/lib/python3.11/site-packages/notify_send-1.1.0.dist-info/*
    /home/mateusz/Software/Spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/python-3.11.0-tabbwylcmzsapq3wvci3xdh7ztalg5vm/lib/python3.11/site-packages/tests/*
Proceed (Y/n)?
```

And the contents of that `tests` folder are:

```bash
$ ls ~/Software/Spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/python-3.11.0-tabbwylcmzsapq3wvci3xdh7ztalg5vm/lib/python3.11/site-packages/tests
__init__.py  __pycache__  test_notification.py
```

I'll submit a PR shortly which should address this issue.

**Comment by andreztz** [comment]
@mbdevpl  I appreciate your observation about the unit tests getting installed along with the package, that's definitely unintended. Your PR has been accepted and the changes are now live. Thanks.
