### ISSUE TITLE
Fails to install PyGObject using Pipenv or Poetry, works using Pip

### ISSUE THREAD

**Issue by jemorriso** [andreztz/notify-send#7]
Not really sure why this is happening, even if I activate a shell in the virtual environment and use its `pip` it still fails. Here is the message:
```
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject which use PEP 517 and cannot be installed directly
```
My system:
pip 21.0.1
python 3.9.2
Kernel: 5.11.5-arch1-1

**Comment by andreztz** [comment]
To install `PyGObject`, the operating system must have some dependencies installed, in the case of Arch Linux the `gobject-introspection` package.

```
sudo pacman -S gobject-introspection
```
